version: '3.8'

services:

  postgres:
    image: postgres
    container_name: postgres
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - "./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:Z"
    environment:
      - POSTGRES_USER=postgres_user_test
      - POSTGRES_PASSWORD=postgres_pwd_test
    networks:
      - gdp-net


networks:
  gdp-net:
    driver: bridge

    driver_opts:
      com.docker.network.driver.mtu: 1450
    